[colors.normal]
black = "#051919"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#859b93"
red = "#e06c75"
white = "#859b93"
yellow = "#d19a66"

[colors.bright]
black = "#546a70"
white = "#e6efff"

[colors.primary]
background = "#051919"
foreground = "#859b93"
