[colors.normal]
black = "#2e3440"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#577499"
red = "#e06c75"
white = "#577499"
yellow = "#d19a66"

[colors.bright]
black = "#333b49"
white = "#e6efff"

[colors.primary]
background = "#2e3440"
foreground = "#577499"
