#!/bin/sh

sxhkd &

picom &

eww open bar

feh --bg-fill ~/Pictures/Wallpaper/wp8.jpg

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config top_padding          44
bspc rule --add Eww manage=off state=floating
