#!/bin/sh

sxhkd &

~/.config/bspwm/cider_autorule.sh &
cider &

picom &

quickshell &

feh --bg-fill ~/Pictures/Wallpaper/wp8.jpg

bspc monitor -d MUSIC 1 2 3 4 5 6 7 8 9 10

bspc rule -a Cider desktop=MUSIC

pgrep -x music-cleaner >/dev/null || (
    music-cleaner() {
        MUSIC_DESK="MUSIC"
        MUSIC_CLASS="Cider"
        while sleep 2; do
            for wid in $(bspc query -N -d "$MUSIC_DESK" -n .window); do
                class=$(bspc query -T -n "$wid" | jq -r '.client.className // empty')
                [ "$class" != "$MUSIC_CLASS" ] && bspc node "$wid" -d next.local
            done
        done
    }
    music-cleaner &
)

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config border_width               4
bspc config window_gap                 8
bspc config focused_border_color       "#77977e"
bspc config normal_border_color        "#313244"
bspc config active_border_color        "#45475a"
bspc config urgent_border_color        "#ff5e5e"
bspc config presel_feedback_color      "#fab387"

bspc rule -a zen border=off
bspc rule -a i3lock state=floating
