[colors.normal]
black = "#4e5174"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#a9afcc"
red = "#e06c75"
white = "#a9afcc"
yellow = "#d19a66"

[colors.bright]
black = "#6a6691"
white = "#e6efff"

[colors.primary]
background = "#4e5174"
foreground = "#a9afcc"
