[colors.normal]
black = "#2f3640"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#6185ac"
red = "#e06c75"
white = "#abb2bf"
yellow = "#d19a66"

[colors.bright]
black = "#625f67"
white = "#e6efff"

[colors.primary]
background = "#2f3640"
foreground = "#6185ac"
