[colors.normal]
black = "#3a373c"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#828791"
yellow = "#d19a66"

[colors.bright]
black = "#5c6370"
white = "#e6efff"

[colors.primary]
background = "#3a373c"
foreground = "#d9c89b"
