#!/bin/bash

spaces (){
    WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
    TEST=$(seq 1 10 | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})')
    T=$(echo "$TEST" | jq -r 'map(select(.windows != 0) .id) | max')    
    C=$(timeout 0.1s ~/.config/eww/scripts/get-active-workspace)
    if [ "$C" -gt "$T" ]; then
        T="$C"
    fi
    seq 1 "$T" | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
}

spaces
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	spaces
done
