#!/bin/bash

ewwPath="$HOME/.config/eww/"
tmpPath="$HOME/.cache/eww/popup"

if [ ! -d $HOME/.cache/eww ]; then
   mkdir ~/.cache/eww
fi

if [ ! -d $tmpPath ]; then
    mkdir $tmpPath;
fi

toggle() {
    if [ -f $tmpPath/"$1" ]; then
        rm $tmpPath/"$1"
        eww -c $ewwPath close $1
    else
        touch $tmpPath/"$1"
        eww -c $ewwPath open $1
    fi
}

# Main
if [ "$1" == "--toggle-music" ]; then
    toggle music-popup-window
fi
