[colors.normal]
black = "#0c1322"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#805794"
red = "#e06c75"
white = "#abb2bf"
yellow = "#d19a66"

[colors.bright]
black = "#403563"
white = "#e6efff"

[colors.primary]
background = "#0c1322"
foreground = "#805794"
